project:
  type: website

website:
  title: "IS415 - Group 5"
  favicon: images/logo.png
  reader-mode: true
  sidebar:
    search: false
  navbar:
    left:
      - text: "Project Proposal"
        href: "proposal/proposal.html"
      - text: "Poster"
        href: "poster/poster.html"
      - text: "Shiny App"
        href: "https://idccy.shinyapps.io/Transit-Ability/"
      - text: "Research Paper"
        href: "research/research_paper.pdf"

    right:
      - icon: github
        href: https://github.com/milktealol/IS415-Project

format:
    
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
