project:
  type: website

website:
  title: "IS415 - Group 5"
  favicon: images/logo.png
  reader-mode: true
  sidebar:
    search: false
  navbar:
    left:
      - text: "Project Proposal"
        href: "proposal/proposal.html"
      - text: "Poster"
        href: "poster/poster.html"
      - text: "Shiny App"
        href: "https://leontanliyang.shinyapps.io/ShinyWorkshopEx/?_ga=2.85313881.170497141.1677572152-999088926.1674193931"
      - text: "Research Paper"
        href: "research/research.html"

    right:
      - icon: github
        href: https://github.com/milktealol/IS415-Project

format:
  pdf: default
  acm-pdf:
    keep-tex: true
    
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

