---
title: "zoe's attempt"
date-modified: "`r Sys.Date()`"
date: "23 February 2023"
execute: 
  message: false
  warning: false
editor: visual
---

# Load packages

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr)
```

# Import data

## Planning Boundary

```{r}
planningBoundaryArea <- st_read(dsn="data/planning-boundary-area.kml")
```

### Plot

```{r}
tm_shape(planningBoundaryArea) +tm_polygons()
```

## Singpapore Subzones

```{r}
mpsz_sf <- st_read(dsn = "data/SingaporeSubzone", 
                layer = "MP14_SUBZONE_WEB_PL")
```

### Check data type

```{r}
st_geometry(mpsz_sf)
```

### Plot

```{r}
tm_shape(mpsz_sf) +tm_polygons() +tm_shape(TrainStations) +tm_dots()
```

## MRT/LRT routes

```{r}
railroutes <- st_read(dsn="data/rail-line.kml")
```

## Train Stations

```{r}
TrainStations <- st_read(dsn = "data/TrainStation_Feb2023", 
                layer = "RapidTransitSystemStation")
```

```{r}
st_geometry(TrainStations)
```

## Population Data

```{r}
popdata<-read_csv("data/ResidentialPopByGeog/hdb-resident-population-by-geographical-distribution.csv")
```

```{r}

```
